import abc

class Transport(abc.ABC):
    @abc.abstractmethod
    def send(self, data: bytes) -> None: ...
    @abc.abstractmethod
    def recv(self) -> bytes: ...
    @abc.abstractmethod
    def close(self) -> None: ...

    @abc.abstractmethod
    def peer_label(self) -> str: ...